name: ISMIR 24/7 Stream
on:
  workflow_dispatch:
  push:

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install FFmpeg
        run: sudo apt update && sudo apt install -y ffmpeg

      - name: Start Streaming
        run: |
          while true; do
            for file in ./*.mp3; do
              echo "Streaming: $file"
              # التعديل الجوهري: استخدام بروتوكول icecast مع اسم المستخدم source
              # هذا هو التنسيق القياسي لسيرفرات Shoutcast
              ffmpeg -re -i "$file" -c:a libmp3lame -b:a 128k -ar 44100 -f mp3 \
              icecast://source:admin2001@82.145.41.50:9210
            done
          done
