name: ISMIR 24/7 Stream
on:
  workflow_dispatch:
  push:

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install FFmpeg
        run: sudo apt update && sudo apt install -y ffmpeg

      - name: Start Streaming
        run: |
          while true; do
            # الكود سيبحث عن كل ملفات mp3 في المستودع ويبثها لسيرفرك
            for file in ./*.mp3; do
              echo "Streaming: $file"
              ffmpeg -re -i "$file" -c:a libmp3lame -b:a 128k -ar 44100 -f mp3 icecast://admin:admin2001@82.145.41.50:9210
            done
          done
